### ISSUE TITLE
Add possibility to specify article language

### ISSUE THREAD

**Issue by IljaN** [yashsinghcodes/wik#11]
Either detect language when full url is passed to -S (br.wikipedia.org) or add a language option which changes the language in the hard coded url here: https://github.com/yashsinghcodes/wik/blob/main/wik/info.py#L42

**Comment by yashsinghcodes** [comment]
I am thinking of adding a new argument for the language like  ```-l``` and then your language code in your case ``` br ``` and a help feature which will list all the language and there respective codes something like ``` list-lang ``` which will list all the language and there codes you can pipe it into grep search for your language.
