### ISSUE TITLE
wik Random Article Feature

### ISSUE THREAD

**Issue by reyg3** [yashsinghcodes/wik#12]
Any interest in including a random wikipedia article feature in wik? I have a basic version of this working but can clean it up and make a PR if you're interested.

**Comment by yashsinghcodes** [comment]
Yea, go for it.

**Comment by reyg3** [comment]
Just submitted PR. I was also thinking getInfo() could have the parameter variable term as optional (term="", lang="en") to allow for a single function to get both specific and random articles. I was thinking of this approach since my PR for getRand() uses your same bs4 logic as getInfo() to return article text. Let me know what you think and if you'd like I can add that random article retrieval to getInfo() in a PR.

**Comment by yashsinghcodes** [comment]
For now lets leave them both as a two different function maybe in future. Thank you so much for the contribution Rey it is really appreciated
