### ISSUE TITLE
wik is *not* a "command based wiki"

### ISSUE THREAD

**Issue by rjmunro** [yashsinghcodes/wik#13]
The README opens with:

> wik is command based wiki.

A wiki is a website where anyone can edit the pages. Wikipedia is one such website. MediaWiki is software for hosting it. Github provides a simple wiki for every project you host (this project even has one: https://github.com/yashsinghcodes/wik/wiki).

wik is (as far as I can see) a tool to view Wikipedia pages from your terminal. The README should say this.

**Comment by yashsinghcodes** [comment]
Done edited thanks for pointing that out. :+1:
