### ISSUE TITLE
Feature Request: Work with offline ZIM files/kiwix

### ISSUE THREAD

**Issue by klundry** [yashsinghcodes/wik#15]
It would be really nice to be able to use wik in conjunction with local offline wikipedia dumps. I'm not a programmer but I'm a big command line enthusiast and I tried modifying the wiki URL in info.py to the local one I'm running. It will display an article when giving the exact name but doesn't return any results when searching. I'm clearly out of my element here :) but it doesn't appear to be too far away from being able to do it.  Thoughts?

**Comment by yashsinghcodes** [comment]
wik is web-scrapping based tool so i don't know if the offline dumps (the one you're talking about) have same elements names (tags,class,id) as the original Wikipedia when searching. I would love to into it if can share the source code of web-page when searching for the article in web-browser.

**Comment by klundry** [comment]
Cool. I'll see if I can paste some of the html that it produces. I'm using kiwix and the CLI tool kiwix-serve to serve the archive and the pages have a more basic and simplified layout that regular wikipedia. If wik can be modified to work with the ZIM files I wonder if it would then work with any of the ZIM files that kiwix has available? That would be pretty neat.

**Comment by yashsinghcodes** [comment]
I don't think so, as they might use different tags and class names for different zim files, for example if you take arch wiki zim files it is totally different in terms of formatting. Hope it makes sense

**Comment by yashsinghcodes** [comment]
The thread is no longer active hence closing. Will look into the feature request in future. Thanks
