### ISSUE TITLE
Search does not work: soup.find('em') returns NoneType

### ISSUE THREAD

**Issue by recursionbane** [yashsinghcodes/wik#16]
Thanks for building this. I see many use-cases for terminal access to Wikipedia post-HTML parse.

In [this routine](https://github.com/yashsinghcodes/wik/blob/7dd7b9ebd4070e4b3a1475948dac67b8288ce17a/wik/info.py#L209),  `soup.find('em')` always returns a `NoneType` in my testing.

```
wik --search Wiki
Result: 

Traceback (most recent call last):
  File "/Users/user/Library/Python/3.9/bin/wik", line 8, in <module>
    sys.exit(arguments())
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/wik/wik.py", line 18, in arguments
    info.searchInfo(a.search)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/wik/info.py", line 222, in searchInfo
    if dym != []: print(dym.get_text())
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by yashsinghcodes** [comment]
Yea, it was bug in code. The `soup.find(em)` function return a NoneType when no em tags are found in the page, so instant of comparing it to NoneType i was mistakenly comparing it to an empty list (which would have been valid if the function was `soup.findall()`). This is what happen when you commit changes without any tests. Anyway i have had fixed it in the latest commit.  Thank-you so much for pointing it out. Let me know if it fixed for you.
