### ISSUE TITLE
error parsing Quotebox

### ISSUE THREAD

**Issue by jklebes** [yashsinghcodes/wik#20]
Nice software.

``wik -i Lahore`` gets me 
```
...
History
---------
[-] Taank Kingdom 550–950Hindu Shahis 1001–1020  Ghaznavid Empire 1020–1186 Delhi Sultanate 1186–1223 Khwarazmian Empire 1223–1228 Delhi Sultanate 1228–1241 Mongol Empire 1241– 1266 Delhi Sultanate 1266–1287 Mongol Empire 1287–1305 Delhi Sultanate 1320–1325 Chagatai Khanate 1329 Khokars 1394–1398 Timurid Empire 1398–1414 Delhi Sultanate 1414–1524 Mughal Empire 1524–1540Suri Empire 1540–1550  Mughal Empire 1550–1739  Afsharid Empire 1739   Durrani Empire 1748–1758   Maratha Empire 1758–1759   Durrani Empire 1759–1765 Sikh Misls 1767–1799   Sikh Empire 1799–1846   British East India Company 1846–1858    British Raj / British Empire 1858–1947   Pakistan 1947– present


Traceback (most recent call last):
  File "/usr/local/bin/wik", line 8, in <module>
    sys.exit(arguments())
  File "/usr/local/lib/python3.10/dist-packages/wik/wik.py", line 24, in arguments
    info.getInfo(a.info, a.lang)
  File "/usr/local/lib/python3.10/dist-packages/wik/info.py", line 136, in getInfo
    if str(i[0]) == "!":
```
This section of content at the bottom of the box
```
<p style="padding-bottom: 0em;"></p>
```
is turned into a zero-length string.

**Comment by yashsinghcodes** [comment]
Thank @jklebes for bringing it to my attention. I will look into it and if you want I can assign it to you :)

**Comment by jklebes** [comment]
You can assign me. But how do you run your unit tests? hatch test test/test.py didn't do it.

**Comment by yashsinghcodes** [comment]
Hey @jklebes, sorry to be late I'll assign you for this :) 

As for the test I don't think it works anymore as wikipedia contents changes time on time it would be hard to implement any direct assertion. Still the script does not run as it is written totally wrong but if you do want to write some more test you are more than welcome to :)

**Comment by yashsinghcodes** [comment]
The code base is very messy so good luck.

**Comment by yashsinghcodes** [comment]
I did write a new test and it should work for now :)

**Comment by yashsinghcodes** [comment]
Sure :+1: 

I'm closing it for now. If in future you face anything similar feel free to reopen it again or you can create a new issue.
