### ISSUE TITLE
Fetch is a very common unix tool

### ISSUE THREAD

**Issue by jepace** [yashsinghcodes/wik#8]
The fetch command has been a fundamental part of the FreeBSD operating system and other OSs for decades.  By naming your project fetch, you risk causing lots of confusion.  Perhaps wikifetch or something would be a better choice?  I love the idea and want to have a command line wikipedia tool!

**Comment by yashsinghcodes** [comment]
Yes James I thinking of changing the name ```wi``` as it is pretty short and my reasearch says it is not taken please let me know if you think it is good name for the tool or wi is already taken by some other program.

**Comment by yashsinghcodes** [comment]
Done changed the name to ```wik```
